import tempfile
import unittest
from pathlib import Path

from multiseat_arch import theme


class ThemeTests(unittest.TestCase):
    def test_restore_native_theme_prefers_backups_and_keeps_backend_hint(self):
        with tempfile.TemporaryDirectory() as tmp:
            home = Path(tmp)
            lxqt = home / ".config/lxqt/lxqt.conf"
            panel = home / ".config/lxqt/panel.conf"
            lxqt.parent.mkdir(parents=True)
            lxqt.write_text("[General]\ntheme=dark\nicon_theme=breeze\n", encoding="utf-8")
            panel.write_text("# Generated by multi-seat-arch.\n[General]\npreferred_backend=labwc:wlroots\n", encoding="utf-8")
            lxqt.with_name("lxqt.conf.msa-backup").write_text("[General]\ntheme=ambiance\n", encoding="utf-8")
            panel.with_name("panel.conf.msa-backup").write_text("[panel1]\nposition=Bottom\n", encoding="utf-8")

            changed = theme.restore_native_lxqt_theme(home)
            self.assertTrue(changed)
            self.assertIn("theme=ambiance", lxqt.read_text(encoding="utf-8"))
            restored_panel = panel.read_text(encoding="utf-8")
            self.assertIn("position=Bottom", restored_panel)
            self.assertIn("preferred_backend=labwc:wlroots", restored_panel)

    def test_generated_theme_files_without_backups_are_removed_or_cleaned(self):
        with tempfile.TemporaryDirectory() as tmp:
            home = Path(tmp)
            lxqt = home / ".config/lxqt/lxqt.conf"
            panel = home / ".config/lxqt/panel.conf"
            kdeglobals = home / ".config/kdeglobals"
            gtk = home / ".config/gtk-3.0/settings.ini"
            lxqt.parent.mkdir(parents=True)
            kdeglobals.parent.mkdir(parents=True, exist_ok=True)
            gtk.parent.mkdir(parents=True, exist_ok=True)

            lxqt.write_text(
                "[General]\ntheme=dark\nicon_theme=breeze\n[Qt]\nstyle=Breeze\n[Palette]\nhighlight_color=#3daee9\n",
                encoding="utf-8",
            )
            panel.write_text(
                "# Generated by multi-seat-arch.\n[General]\npreferred_backend=labwc:wlroots\n",
                encoding="utf-8",
            )
            kdeglobals.write_text(
                "[General]\nColorScheme=BreezeDark\n[Colors:Window]\nBackgroundNormal=32,33,36\n[Colors:View]\nDecorationFocus=61,174,233\n",
                encoding="utf-8",
            )
            gtk.write_text(
                "[Settings]\ngtk-theme-name=Breeze-Dark\ngtk-icon-theme-name=breeze\ngtk-cursor-theme-name=breeze_cursors\n",
                encoding="utf-8",
            )

            theme.restore_native_lxqt_theme(home)
            lxqt_text = lxqt.read_text(encoding="utf-8")
            self.assertNotIn("theme=dark", lxqt_text)
            self.assertNotIn("style=Breeze", lxqt_text)
            self.assertFalse(kdeglobals.exists())
            self.assertFalse(gtk.exists())
            # A fresh panel may be absent after removing our generated one.
            self.assertFalse(panel.exists())

    def test_rollback_is_idempotent_and_does_not_retheme_user(self):
        with tempfile.TemporaryDirectory() as tmp:
            home = Path(tmp)
            panel = home / ".config/lxqt/panel.conf"
            panel.parent.mkdir(parents=True)
            panel.write_text("[panel1]\nposition=Bottom\n", encoding="utf-8")

            self.assertTrue(theme.restore_native_lxqt_theme(home))
            panel.write_text("[General]\npreferred_backend=labwc:wlroots\n[panel1]\ntheme=frost\n", encoding="utf-8")
            self.assertFalse(theme.restore_native_lxqt_theme(home))
            self.assertIn("theme=frost", panel.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
