from __future__ import annotations

import json
import re
from pathlib import Path
from types import ModuleType

AUDIO_CONFIG = Path("/etc/multi-seat-arch/audio.json")
RUNTIME_AUDIO_UDEV_RULES = Path("/run/udev/rules.d/99-multi-seat-arch-runtime-audio.rules")
LEGACY_RUNTIME_AUDIO_UDEV_RULES = Path("/run/udev/rules.d/74-multi-seat-arch-runtime-audio.rules")

_PCI_SINK_RE = re.compile(
    r"pci-(?P<domain>[0-9a-fA-F]{4})_(?P<bus>[0-9a-fA-F]{2})_(?P<slot>[0-9a-fA-F]{2})\.(?P<func>[0-7])"
)


def _pci_from_sink_name(name: str) -> str:
    match = _PCI_SINK_RE.search(name)
    if not match:
        return ""
    return (
        f"{match.group('domain')}:{match.group('bus')}:"
        f"{match.group('slot')}.{match.group('func')}"
    ).lower()


def _load_audio_rules() -> list[dict[str, str]]:
    try:
        raw = json.loads(AUDIO_CONFIG.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    outputs = raw.get("outputs", []) if isinstance(raw, dict) else []
    result: list[dict[str, str]] = []
    for item in outputs if isinstance(outputs, list) else []:
        if not isinstance(item, dict):
            continue
        output = str(item.get("output") or "").strip()
        seat = str(item.get("seat") or "").strip()
        if output and seat in {"seat-a", "seat-b"}:
            result.append({"output": output, "seat": seat})
    return result


def _runtime_for_logical(config, backend: ModuleType, logical: str) -> str:
    for seat in config.seats:
        if seat.enabled and seat.name == logical:
            return backend.runtime_seat_name(seat)
    return ""


def _reload_sound(backend: ModuleType) -> None:
    backend._run(["udevadm", "control", "--reload"], check=False)
    backend._run(["udevadm", "trigger", "--subsystem-match=sound", "--action=change"], check=False)
    backend._run(["udevadm", "settle", "--timeout=5"], check=False)


def apply_runtime_audio_seats(config, backend: ModuleType) -> None:
    """Move PCI/ALSA audio hardware to the logind seat selected in the GUI.

    The seat assignment itself is not enough when a local user belongs to the
    traditional `audio` group: that group grants direct rw access to /dev/snd
    and bypasses logind's per-seat ACLs. While multiseat is active, managed
    sound nodes therefore use group root and rely on logind/uaccess ACLs for the
    active user of the owning seat. The runtime rule is removed on restore or
    reboot, at which point the distro's normal sound permissions are restored.
    """
    assignments: dict[str, str] = {}
    for rule in _load_audio_rules():
        pci = _pci_from_sink_name(rule["output"])
        if not pci:
            # Bluetooth and virtual outputs are not /dev/snd PCI hardware and
            # stay managed by the owning user's WirePlumber.
            continue
        runtime = _runtime_for_logical(config, backend, rule["seat"])
        if runtime:
            assignments[pci] = runtime

    RUNTIME_AUDIO_UDEV_RULES.parent.mkdir(parents=True, exist_ok=True)
    LEGACY_RUNTIME_AUDIO_UDEV_RULES.unlink(missing_ok=True)

    if not assignments:
        RUNTIME_AUDIO_UDEV_RULES.unlink(missing_ok=True)
        _reload_sound(backend)
        return

    lines = ["# Generated by multi-seat-arch; removed on restore/reboot."]
    for pci, runtime in sorted(assignments.items()):
        seat = runtime.replace("\\", "\\\\").replace('"', '\\"')
        dev = pci.replace("\\", "\\\\").replace('"', '\\"')
        # This late rule intentionally overrides the normal audio group on
        # managed ALSA nodes. TAG+=uaccess keeps logind ACL management active.
        lines.append(
            f'SUBSYSTEM=="sound", KERNELS=="{dev}", '
            f'ENV{{ID_SEAT}}="{seat}", GROUP="root", MODE="0660", '
            f'TAG+="seat", TAG+="uaccess"'
        )
        lines.append(
            f'SUBSYSTEM=="sound", KERNEL=="card*", KERNELS=="{dev}", '
            f'ENV{{ID_SEAT}}="{seat}", GROUP="root", MODE="0660", '
            f'TAG+="seat", TAG+="master-of-seat", TAG+="uaccess"'
        )

    tmp = RUNTIME_AUDIO_UDEV_RULES.with_suffix(".tmp")
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(RUNTIME_AUDIO_UDEV_RULES)
    _reload_sound(backend)


def clear_runtime_audio_seats(backend: ModuleType) -> None:
    for path in (RUNTIME_AUDIO_UDEV_RULES, LEGACY_RUNTIME_AUDIO_UDEV_RULES):
        try:
            path.unlink(missing_ok=True)
        except OSError:
            pass
    _reload_sound(backend)
