from __future__ import annotations

import json
import re
from pathlib import Path
from types import ModuleType

AUDIO_CONFIG = Path("/etc/multi-seat-arch/audio.json")
RUNTIME_AUDIO_UDEV_RULES = Path("/run/udev/rules.d/74-multi-seat-arch-runtime-audio.rules")

_PCI_SINK_RE = re.compile(
    r"pci-(?P<domain>[0-9a-fA-F]{4})_(?P<bus>[0-9a-fA-F]{2})_(?P<slot>[0-9a-fA-F]{2})\.(?P<func>[0-7])"
)


def _pci_from_sink_name(name: str) -> str:
    match = _PCI_SINK_RE.search(name)
    if not match:
        return ""
    return (
        f"{match.group('domain')}:{match.group('bus')}:"
        f"{match.group('slot')}.{match.group('func')}"
    ).lower()


def _load_audio_rules() -> list[dict[str, str]]:
    try:
        raw = json.loads(AUDIO_CONFIG.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    outputs = raw.get("outputs", []) if isinstance(raw, dict) else []
    result: list[dict[str, str]] = []
    for item in outputs if isinstance(outputs, list) else []:
        if not isinstance(item, dict):
            continue
        output = str(item.get("output") or "").strip()
        seat = str(item.get("seat") or "").strip()
        if output and seat in {"seat-a", "seat-b"}:
            result.append({"output": output, "seat": seat})
    return result


def _runtime_for_logical(config, backend: ModuleType, logical: str) -> str:
    for seat in config.seats:
        if seat.enabled and seat.name == logical:
            return backend.runtime_seat_name(seat)
    return ""


def apply_runtime_audio_seats(config, backend: ModuleType) -> None:
    """Move PCI/ALSA audio hardware to the logind seat selected in the GUI.

    PipeWire/WirePlumber run per user. Without assigning the physical ALSA
    device to a seat, the first logged-in user can obtain every /dev/snd node
    and the other seat sees no audio devices at all. The sink name generated by
    PipeWire contains the stable PCI address (for example
    alsa_output.pci-0000_04_00.6.analog-stereo), which is sufficient to bind all
    sound children of that PCI function to the intended runtime seat.
    """
    assignments: dict[str, str] = {}
    for rule in _load_audio_rules():
        pci = _pci_from_sink_name(rule["output"])
        if not pci:
            # Bluetooth and virtual outputs are not /dev/snd PCI hardware and
            # must remain handled by the owning user's WirePlumber.
            continue
        runtime = _runtime_for_logical(config, backend, rule["seat"])
        if runtime:
            assignments[pci] = runtime

    RUNTIME_AUDIO_UDEV_RULES.parent.mkdir(parents=True, exist_ok=True)
    if not assignments:
        RUNTIME_AUDIO_UDEV_RULES.unlink(missing_ok=True)
        backend._run(["udevadm", "control", "--reload"], check=False)
        backend._run(["udevadm", "trigger", "--subsystem-match=sound", "--action=change"], check=False)
        backend._run(["udevadm", "settle", "--timeout=5"], check=False)
        return

    lines = ["# Generated by multi-seat-arch; removed on restore/reboot."]
    for pci, runtime in sorted(assignments.items()):
        seat = runtime.replace("\\", "\\\\").replace('"', '\\"')
        dev = pci.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'SUBSYSTEM=="sound", KERNELS=="{dev}", '
            f'ENV{{ID_SEAT}}="{seat}", TAG+="seat"'
        )
        lines.append(
            f'SUBSYSTEM=="sound", KERNEL=="card*", KERNELS=="{dev}", '
            f'ENV{{ID_SEAT}}="{seat}", TAG+="seat", TAG+="master-of-seat"'
        )

    tmp = RUNTIME_AUDIO_UDEV_RULES.with_suffix(".tmp")
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(RUNTIME_AUDIO_UDEV_RULES)

    backend._run(["udevadm", "control", "--reload"], check=False)
    backend._run(["udevadm", "trigger", "--subsystem-match=sound", "--action=change"], check=False)
    backend._run(["udevadm", "settle", "--timeout=5"], check=False)


def clear_runtime_audio_seats(backend: ModuleType) -> None:
    try:
        RUNTIME_AUDIO_UDEV_RULES.unlink(missing_ok=True)
    except OSError:
        pass
    backend._run(["udevadm", "control", "--reload"], check=False)
    backend._run(["udevadm", "trigger", "--subsystem-match=sound", "--action=change"], check=False)
    backend._run(["udevadm", "settle", "--timeout=5"], check=False)
