from __future__ import annotations

import json
import re
from pathlib import Path
from types import ModuleType

AUDIO_CONFIG = Path("/etc/multi-seat-arch/audio.json")
RUNTIME_AUDIO_UDEV_RULES = Path("/run/udev/rules.d/74-multi-seat-arch-runtime-audio.rules")

_PCI_SINK_RE = re.compile(
    r"pci-(?P<domain>[0-9a-fA-F]{4})_(?P<bus>[0-9a-fA-F]{2})_(?P<slot>[0-9a-fA-F]{2})\.(?P<func>[0-7])"
)
_SEAT_RE = re.compile(r"seat-[A-Za-z0-9_-]+$")


def _pci_from_sink_name(name: str) -> str:
    match = _PCI_SINK_RE.search(name)
    if not match:
        return ""
    return (
        f"{match.group('domain')}:{match.group('bus')}:"
        f"{match.group('slot')}.{match.group('func')}"
    ).lower()


def _load_audio_rules() -> list[dict[str, str]]:
    try:
        raw = json.loads(AUDIO_CONFIG.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    outputs = raw.get("outputs", []) if isinstance(raw, dict) else []
    result: list[dict[str, str]] = []
    for item in outputs if isinstance(outputs, list) else []:
        if not isinstance(item, dict):
            continue
        output = str(item.get("output") or "").strip()
        seat = str(item.get("seat") or "").strip()
        if output and _SEAT_RE.fullmatch(seat):
            result.append({"output": output, "seat": seat})
    return result


def _runtime_for_logical(config, backend: ModuleType, logical: str) -> str:
    for seat in config.seats:
        if seat.enabled and seat.name == logical:
            return backend.runtime_seat_name(seat)
    return ""


def apply_runtime_audio_seats(config, backend: ModuleType) -> None:
    """Move PCI/ALSA audio hardware to the logind seat selected in the GUI."""
    assignments: dict[str, str] = {}
    owners: dict[str, str] = {}
    for rule in _load_audio_rules():
        pci = _pci_from_sink_name(rule["output"])
        if not pci:
            # Bluetooth and virtual outputs are not /dev/snd PCI hardware.
            continue
        runtime = _runtime_for_logical(config, backend, rule["seat"])
        if not runtime:
            continue
        existing = assignments.get(pci)
        if existing is not None and existing != runtime:
            raise RuntimeError(
                "Duas saídas do mesmo hardware ALSA/PCI foram atribuídas a seats diferentes: "
                f"{pci} ({owners[pci]} -> {existing}, {rule['seat']} -> {runtime}). "
                "Um controlador físico de áudio só pode pertencer a um seat por vez."
            )
        assignments[pci] = runtime
        owners[pci] = rule["seat"]

    RUNTIME_AUDIO_UDEV_RULES.parent.mkdir(parents=True, exist_ok=True)
    if not assignments:
        RUNTIME_AUDIO_UDEV_RULES.unlink(missing_ok=True)
        backend._run(["udevadm", "control", "--reload"], check=False)
        backend._run(["udevadm", "trigger", "--subsystem-match=sound", "--action=change"], check=False)
        backend._run(["udevadm", "settle", "--timeout=5"], check=False)
        return

    lines = ["# Generated by multi-seat-arch; removed on restore/reboot."]
    for pci, runtime in sorted(assignments.items()):
        seat = runtime.replace("\\", "\\\\").replace('"', '\\"')
        dev = pci.replace("\\", "\\\\").replace('"', '\\"')
        # Override the normal audio group while multiseat is active. Otherwise a
        # user in the global `audio` group can bypass logind seat ACLs.
        lines.append(
            f'SUBSYSTEM=="sound", KERNELS=="{dev}", '
            f'ENV{{ID_SEAT}}="{seat}", GROUP="root", MODE="0660", '
            'TAG+="seat", TAG+="uaccess"'
        )
        lines.append(
            f'SUBSYSTEM=="sound", KERNEL=="card*", KERNELS=="{dev}", '
            f'ENV{{ID_SEAT}}="{seat}", GROUP="root", MODE="0660", '
            'TAG+="seat", TAG+="master-of-seat", TAG+="uaccess"'
        )

    tmp = RUNTIME_AUDIO_UDEV_RULES.with_suffix(".tmp")
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(RUNTIME_AUDIO_UDEV_RULES)

    backend._run(["udevadm", "control", "--reload"], check=False)
    backend._run(["udevadm", "trigger", "--subsystem-match=sound", "--action=change"], check=False)
    backend._run(["udevadm", "settle", "--timeout=5"], check=False)


def clear_runtime_audio_seats(backend: ModuleType) -> None:
    try:
        RUNTIME_AUDIO_UDEV_RULES.unlink(missing_ok=True)
    except OSError:
        pass
    backend._run(["udevadm", "control", "--reload"], check=False)
    backend._run(["udevadm", "trigger", "--subsystem-match=sound", "--action=change"], check=False)
    backend._run(["udevadm", "settle", "--timeout=5"], check=False)
