from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

from .audio import load_rules


_BT_ADDRESS_RE = re.compile(
    r"(?<![0-9A-Fa-f])([0-9A-Fa-f]{2}(?:[:_-][0-9A-Fa-f]{2}){5})(?![0-9A-Fa-f])"
)


def _run(command: list[str], timeout: float = 8.0) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout,
        )
    except (OSError, subprocess.TimeoutExpired):
        return subprocess.CompletedProcess(command, 127, "")


def _is_bluetooth_output(name: str) -> bool:
    value = name.strip().lower()
    return value.startswith("bluez_") or "bluez_output." in value or "bluez_input." in value


def _bluetooth_address_from_output(name: str) -> str:
    """Return a stable BlueZ/WirePlumber address token (AA_BB_CC_DD_EE_FF)."""
    if not _is_bluetooth_output(name):
        return ""
    match = _BT_ADDRESS_RE.search(name)
    if not match:
        return ""
    octets = re.split(r"[:_-]", match.group(1))
    return "_".join(part.upper() for part in octets)


def _logical_seat_for_current_session() -> str:
    runtime_seat = os.environ.get("XDG_SEAT", "").strip()
    if not runtime_seat:
        return ""

    from . import config as cfg
    from .backend import runtime_seat_name

    try:
        config = cfg.load()
    except Exception:
        return ""

    return next(
        (
            seat.name
            for seat in config.seats
            if seat.enabled and runtime_seat_name(seat) == runtime_seat
        ),
        "",
    )


def _device_owners() -> dict[str, str]:
    """Map each configured Bluetooth device address to its logical seat."""
    owners: dict[str, str] = {}
    for rule in load_rules():
        if rule.seat == "unmanaged":
            continue
        address = _bluetooth_address_from_output(rule.output)
        if not address:
            continue
        previous = owners.get(address)
        if previous is not None and previous != rule.seat:
            raise RuntimeError(
                f"Dispositivo Bluetooth {address} foi atribuído a dois seats: "
                f"{previous} e {rule.seat}."
            )
        owners[address] = rule.seat
    return owners


def _wireplumber_search_path(runtime_cfg: Path) -> str:
    home = Path.home()
    xdg_config_home = Path(os.environ.get("XDG_CONFIG_HOME") or (home / ".config"))
    candidates = [
        runtime_cfg,
        xdg_config_home / "wireplumber",
        Path("/etc/xdg/wireplumber"),
        Path("/etc/wireplumber"),
        Path("/usr/local/share/wireplumber"),
        Path("/usr/share/wireplumber"),
    ]
    return ":".join(str(path) for path in candidates)


def _wireplumber_fragment(logical: str, owners: dict[str, str]) -> str:
    """Generate a per-session allow/deny policy without owning the adapter.

    Every seat keeps a BlueZ monitor so different Bluetooth audio devices can be
    used concurrently through one controller. Devices explicitly assigned to a
    different seat are disabled before WirePlumber creates their audio nodes.
    Unmanaged devices keep the normal distro behaviour until the user assigns
    them in Multi Seat Arch.
    """
    lines = [
        "# Generated by multi-seat-arch for this login session.",
        "wireplumber.profiles = {",
        "  main = {",
        "    monitor.bluez = required",
        "    monitor.bluez-midi = optional",
        "    monitor.bluez.seat-monitoring = disabled",
        "  }",
        "}",
    ]

    blocked = sorted(address for address, owner in owners.items() if owner != logical)
    if blocked:
        lines.extend(["", "monitor.bluez.rules = ["])
        for address in blocked:
            lines.extend(
                [
                    "  {",
                    "    matches = [",
                    f'      {{ device.name = "bluez_card.{address}" }}',
                    "    ]",
                    "    actions = {",
                    "      update-props = {",
                    "        device.disabled = true",
                    "      }",
                    "    }",
                    "  }",
                ]
            )
        lines.append("]")
    return "\n".join(lines) + "\n"


def configure_for_current_seat() -> None:
    """Apply persistent Bluetooth-audio ownership per physical device.

    BlueZ remains global and shared. Only the PipeWire/WirePlumber representation
    is filtered per login session, which scales to multiple headsets assigned to
    different seats without making one seat the owner of the whole adapter.

    Bluetooth HID peripherals (mouse, keyboard, gamepad, etc.) do not travel
    through PipeWire; they continue through the generic evdev/udev peripheral
    routing and hotplug watcher, so they can be assigned independently as well.
    """
    logical = _logical_seat_for_current_session()
    if not logical:
        return

    owners = _device_owners()
    if not owners:
        return

    user_runtime = Path(os.environ.get("XDG_RUNTIME_DIR") or f"/run/user/{os.getuid()}")
    runtime_cfg = user_runtime / "multi-seat-arch" / "wireplumber"
    fragment_dir = runtime_cfg / "wireplumber.conf.d"
    fragment_dir.mkdir(parents=True, exist_ok=True)
    fragment = fragment_dir / "90-multi-seat-arch-bluetooth-seat.conf"
    fragment.write_text(_wireplumber_fragment(logical, owners), encoding="utf-8")

    systemctl = shutil.which("systemctl")
    if not systemctl:
        return

    search_path = _wireplumber_search_path(runtime_cfg)
    _run(
        [systemctl, "--user", "set-environment", f"WIREPLUMBER_CONFIG_DIR={search_path}"],
        timeout=4.0,
    )
    os.environ["WIREPLUMBER_CONFIG_DIR"] = search_path
    _run([systemctl, "--user", "restart", "wireplumber.service"], timeout=8.0)


def clear_for_current_user() -> None:
    """Remove the transient Bluetooth policy when the leased session exits."""
    user_runtime = Path(os.environ.get("XDG_RUNTIME_DIR") or f"/run/user/{os.getuid()}")
    runtime_cfg = user_runtime / "multi-seat-arch" / "wireplumber"
    fragment = runtime_cfg / "wireplumber.conf.d" / "90-multi-seat-arch-bluetooth-seat.conf"
    try:
        fragment.unlink(missing_ok=True)
    except OSError:
        pass

    systemctl = shutil.which("systemctl")
    if not systemctl:
        return
    _run([systemctl, "--user", "unset-environment", "WIREPLUMBER_CONFIG_DIR"], timeout=4.0)
    _run([systemctl, "--user", "restart", "wireplumber.service"], timeout=8.0)
