from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

from .audio import load_rules


def _run(command: list[str], timeout: float = 8.0) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout,
        )
    except (OSError, subprocess.TimeoutExpired):
        return subprocess.CompletedProcess(command, 127, "")


def _is_bluetooth_output(name: str) -> bool:
    value = name.strip().lower()
    return value.startswith("bluez_") or "bluez_output." in value or "bluez_input." in value


def _logical_seat_for_current_session() -> str:
    runtime_seat = os.environ.get("XDG_SEAT", "").strip()
    if not runtime_seat:
        return ""

    from . import config as cfg
    from .backend import runtime_seat_name

    try:
        config = cfg.load()
    except Exception:
        return ""

    return next(
        (
            seat.name
            for seat in config.seats
            if seat.enabled and runtime_seat_name(seat) == runtime_seat
        ),
        "",
    )


def _wireplumber_search_path(runtime_cfg: Path) -> str:
    home = Path.home()
    xdg_config_home = Path(os.environ.get("XDG_CONFIG_HOME") or (home / ".config"))
    candidates = [
        runtime_cfg,
        xdg_config_home / "wireplumber",
        Path("/etc/xdg/wireplumber"),
        Path("/etc/wireplumber"),
        Path("/usr/local/share/wireplumber"),
        Path("/usr/share/wireplumber"),
    ]
    # Keep non-existing locations too: WirePlumber safely skips them and this
    # preserves the normal lookup order when a directory later appears.
    return ":".join(str(path) for path in candidates)


def configure_for_current_seat() -> None:
    """Make Bluetooth audio ownership deterministic in multiseat sessions.

    BlueZ is system-wide, while every logged-in user runs its own WirePlumber.
    With two active seats, both WirePlumber instances can race to claim a newly
    reconnected headset. The GUI assignment is persistent, so select exactly
    one logical seat as the Bluetooth-audio owner and disable the BlueZ monitor
    on the other sessions. This keeps reconnects on the configured seat instead
    of whichever user happened to win the race.
    """
    logical = _logical_seat_for_current_session()
    if not logical:
        return

    bluetooth_rules = [rule for rule in load_rules() if _is_bluetooth_output(rule.output)]
    if not bluetooth_rules:
        return

    owners = {rule.seat for rule in bluetooth_rules if rule.seat != "unmanaged"}
    if not owners:
        return

    # A single system BlueZ stack cannot be reliably split between independent
    # per-user WirePlumber instances. If multiple Bluetooth sinks were assigned
    # to different seats, prefer the first configured owner deterministically.
    owner = next(rule.seat for rule in bluetooth_rules if rule.seat != "unmanaged")

    user_runtime = Path(os.environ.get("XDG_RUNTIME_DIR") or f"/run/user/{os.getuid()}")
    runtime_cfg = user_runtime / "multi-seat-arch" / "wireplumber"
    fragment_dir = runtime_cfg / "wireplumber.conf.d"
    fragment_dir.mkdir(parents=True, exist_ok=True)
    fragment = fragment_dir / "90-multi-seat-arch-bluetooth-seat.conf"

    if logical == owner:
        content = """# Generated by multi-seat-arch for this login session.\nwireplumber.profiles = {\n  main = {\n    monitor.bluez = required\n    monitor.bluez-midi = optional\n    monitor.bluez.seat-monitoring = disabled\n  }\n}\n"""
    else:
        content = """# Generated by multi-seat-arch for this login session.\nwireplumber.profiles = {\n  main = {\n    monitor.bluez = disabled\n    monitor.bluez-midi = disabled\n    monitor.bluez.seat-monitoring = disabled\n  }\n}\n"""

    fragment.write_text(content, encoding="utf-8")

    systemctl = shutil.which("systemctl")
    if not systemctl:
        return

    search_path = _wireplumber_search_path(runtime_cfg)
    _run([systemctl, "--user", "set-environment", f"WIREPLUMBER_CONFIG_DIR={search_path}"], timeout=4.0)
    os.environ["WIREPLUMBER_CONFIG_DIR"] = search_path

    # WirePlumber reads monitor features only at startup. Restarting only the
    # session manager leaves PipeWire itself and the graphical session intact.
    _run([systemctl, "--user", "restart", "wireplumber.service"], timeout=8.0)


def clear_for_current_user() -> None:
    """Remove the transient seat policy when the custom Plasma session exits."""
    user_runtime = Path(os.environ.get("XDG_RUNTIME_DIR") or f"/run/user/{os.getuid()}")
    runtime_cfg = user_runtime / "multi-seat-arch" / "wireplumber"
    fragment = runtime_cfg / "wireplumber.conf.d" / "90-multi-seat-arch-bluetooth-seat.conf"
    try:
        fragment.unlink(missing_ok=True)
    except OSError:
        pass

    systemctl = shutil.which("systemctl")
    if not systemctl:
        return
    _run([systemctl, "--user", "unset-environment", "WIREPLUMBER_CONFIG_DIR"], timeout=4.0)
    _run([systemctl, "--user", "restart", "wireplumber.service"], timeout=8.0)
