from __future__ import annotations

import os
import shutil
from pathlib import Path

MODE_FILE = Path("/etc/multi-seat-arch/dynamic-login")
ATRIUM_CONFIG = Path("/etc/atrium.conf")
ATRIUM_BINARY = Path("/usr/bin/atrium")


def enabled() -> bool:
    return MODE_FILE.exists()


def _write_atomic(path: Path, text: str, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    try:
        tmp.write_text(text, encoding="utf-8")
        os.chmod(tmp, mode)
        tmp.replace(path)
    finally:
        tmp.unlink(missing_ok=True)


def _canonical(path: str | Path) -> str:
    return str(Path(path).resolve(strict=True))


def _resolve_wrapper(name: str) -> str:
    found = shutil.which(name)
    if found and Path(found).is_file():
        return _canonical(found)

    for candidate in (Path("/usr/bin") / name, Path("/usr/local/bin") / name):
        if candidate.is_file():
            return _canonical(candidate)

    raise RuntimeError(
        f"Wrapper de login ausente: {name}. Reinstale o projeto com: "
        "bash scripts/install.sh"
    )


def _resolve_sddm_greeter() -> str:
    for name in (
        "sddm-greeter-qt6",
        "sddm-greeter",
        "/usr/lib/sddm/sddm-greeter-qt6",
        "/usr/lib/sddm/sddm-greeter",
    ):
        found = shutil.which(name) if not name.startswith("/") else name
        if found and Path(found).is_file() and os.access(found, os.X_OK):
            return _canonical(found)
    raise RuntimeError(
        "Greeter do SDDM/KDE ausente. Reinstale com bash scripts/install.sh "
        "ou instale o pacote sddm."
    )


def prerequisites() -> dict[str, str]:
    """Return canonical paths required by the dynamic-login backend."""
    if not ATRIUM_BINARY.is_file():
        raise RuntimeError(
            "Atrium multiseat não está instalado. Rode scripts/build-atrium-login-manager.sh primeiro."
        )
    return {
        "atrium": _canonical(ATRIUM_BINARY),
        "sddm_greeter": _resolve_sddm_greeter(),
        "greeter_wrapper": _resolve_wrapper("multi-seat-arch-login-greeter"),
        "plasma_wrapper": _resolve_wrapper("multi-seat-arch-login-plasma"),
    }


def enable() -> None:
    if os.geteuid() != 0:
        raise PermissionError("Execute como root.")

    paths = prerequisites()
    greeter_wrapper = paths["greeter_wrapper"]
    plasma_wrapper = paths["plasma_wrapper"]

    # Atrium owns only the synthetic display seats created by Multi Seat Arch.
    # seat0 remains reserved for the normal desktop/display manager used by restore.
    # The greeter wrapper presents the stock KDE/SDDM UI and translates its
    # authentication request to Atrium's PAM/session backend.
    config = f"""# Generated by Multi Seat Arch dynamic-login mode.
# Each physical display seat gets an independent KDE/SDDM greeter and can
# authenticate any local user through Atrium/PAM. The old seat.user fields are
# ignored at runtime.

greeter = {greeter_wrapper}
compositor = {plasma_wrapper}
desktop = KDE
allow-duplicate-login = false
ignore-seat = seat0

crash-restart-delay = 1000
crash-count-limit = 5
crash-window = 60
drm-backoff = 500
"""
    _write_atomic(ATRIUM_CONFIG, config)
    _write_atomic(MODE_FILE, "atrium-kde-sddm-v2\n")


def disable() -> None:
    if os.geteuid() != 0:
        raise PermissionError("Execute como root.")
    MODE_FILE.unlink(missing_ok=True)
