from __future__ import annotations

import os
import time
from pathlib import Path
from types import ModuleType

DIAG = Path("/var/log/multi-seat-arch-last-diagnostic.log")


def install(backend: ModuleType) -> None:
    if getattr(backend, "_msa_runtime_patch_v2_installed", False):
        return

    original_persist = backend._persist_activation_error

    def event_children(parent: str) -> list[str]:
        path = Path(parent)
        return [str(p) for p in sorted(path.glob("event*")) if p.name.startswith("event")]

    def write_rules(config, assignments: list[tuple[str, str]]) -> None:
        target = backend.RUNTIME_UDEV_RULES
        target.parent.mkdir(parents=True, exist_ok=True)
        lines = ["# Generated by multi-seat-arch; removed on restore/reboot."]

        for seat in backend.active_seats(config):
            runtime = backend.runtime_seat_name(seat)
            phys = backend._udev_escape(f"multi-seat-arch/{runtime}")
            value = backend._udev_escape(runtime)
            lines.append(
                f'SUBSYSTEM=="input", KERNEL=="input*", ATTR{{phys}}=="{phys}", '
                f'ENV{{ID_SEAT}}="{value}", TAG+="seat", TAG+="master-of-seat"'
            )
            lines.append(
                f'SUBSYSTEM=="input", KERNEL=="event*", ATTRS{{phys}}=="{phys}", '
                f'ENV{{ID_SEAT}}="{value}", TAG+="seat"'
            )

        for runtime, syspath in sorted(set(assignments)):
            kernel = Path(syspath).name
            if not syspath.startswith("/sys/devices/") or not kernel.startswith("input"):
                raise RuntimeError(f"Input inválido: {syspath}")
            devpath = backend._udev_escape(syspath.removeprefix("/sys"))
            value = backend._udev_escape(runtime)
            lines.append(
                f'SUBSYSTEM=="input", KERNEL=="{kernel}", DEVPATH=="{devpath}", '
                f'ENV{{ID_SEAT}}="{value}", TAG+="seat", TAG+="master-of-seat"'
            )
            # libinput opens eventN, not inputN.  The previous implementation
            # tagged only the parent and produced two working displays with
            # completely frozen keyboards/mice on systemd 261.
            lines.append(
                f'SUBSYSTEM=="input", KERNEL=="event*", KERNELS=="{kernel}", '
                f'DEVPATH=="{devpath}/event*", ENV{{ID_SEAT}}="{value}", TAG+="seat"'
            )

        tmp = target.with_suffix(".tmp")
        tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
        os.replace(tmp, target)
        backend._run(["udevadm", "control", "--reload"], check=False)
        backend._run(["udevadm", "trigger", "--subsystem-match=input", "--action=change"], check=False)
        backend._run(["udevadm", "settle", "--timeout=5"], check=False)

    def wait_assignments(assignments: list[tuple[str, str]], timeout: float = 8.0) -> None:
        expected: set[tuple[str, str]] = set()
        for seat, parent in assignments:
            children = event_children(parent)
            expected.update((seat, p) for p in (children or [parent]))
        deadline = time.monotonic() + timeout
        pending = set(expected)
        while pending and time.monotonic() < deadline:
            pending = {(seat, p) for seat, p in pending if backend._udev_seat(p) != seat}
            if pending:
                time.sleep(0.1)
        if pending:
            detail = ", ".join(f"{p} -> {seat}" for seat, p in sorted(pending))
            raise RuntimeError("udev não aplicou ID_SEAT aos event nodes: " + detail)

    def diagnostic(config=None) -> str:
        chunks: list[str] = []
        for title, cmd in [
            ("SESSIONS", ["loginctl", "list-sessions", "--no-legend"]),
            ("SEATS", ["loginctl", "list-seats", "--no-legend"]),
            ("UNITS", ["systemctl", "list-units", "--all", "--plain", "--no-legend", "msa-*"]),
        ]:
            chunks.append(f"\n--- {title} ---\n{backend._run(cmd, check=False).stdout.strip()}\n")
        if config is not None:
            for seat in backend.active_seats(config):
                runtime = backend.runtime_seat_name(seat)
                out = backend._run(["loginctl", "seat-status", runtime], check=False).stdout.strip()
                chunks.append(f"\n--- {runtime} ---\n{out}\n")
        for unit in backend._list_units(("msa-seat-", "msa-dlm-", "msa-input-")):
            out = backend._run(["journalctl", "-u", unit, "-b", "--no-pager", "-o", "cat", "-n", "120"], check=False).stdout.strip()
            chunks.append(f"\n--- {unit} ---\n{out}\n")
        return "".join(chunks)

    def save_diag(config=None) -> None:
        try:
            DIAG.write_text(time.strftime("%Y-%m-%d %H:%M:%S") + "\n" + diagnostic(config), encoding="utf-8")
        except Exception:
            pass

    def persist(exc: BaseException) -> None:
        original_persist(exc)
        try:
            with backend.LAST_ERROR.open("a", encoding="utf-8") as handle:
                handle.write(diagnostic())
        except Exception:
            pass

    def release_seat0() -> None:
        backend._run(["systemctl", "isolate", "multi-user.target"], check=False, timeout=30)
        backend._run(["systemctl", "stop", "display-manager.service"], check=False, timeout=20)
        backend._run(["loginctl", "terminate-seat", "seat0"], check=False, timeout=20)
        time.sleep(2.0)

    def activate(config) -> None:
        if os.geteuid() != 0:
            raise PermissionError("Execute como root.")
        backend._run(["systemctl", "stop", backend.RESTORE_UNIT], check=False)
        errors = backend.validate(config)
        if errors:
            raise RuntimeError("\n".join(errors))
        missing = [c.message for c in backend.doctor(config) if not c.ok]
        if missing:
            raise RuntimeError("Pré-validação falhou: " + ", ".join(missing))
        try:
            backend.LAST_ERROR.unlink(missing_ok=True)
            DIAG.unlink(missing_ok=True)
            backend.stop_transient_units(exclude={backend.ACTIVATE_UNIT, backend.RESTORE_UNIT}, include_legacy=True)
            release_seat0()
            dlm = backend._resolve_binary("drm-lease-manager", "/usr/local/bin/drm-lease-manager")
            if not dlm:
                raise RuntimeError("drm-lease-manager não encontrado.")
            seats = backend.active_seats(config)
            for card in sorted({s.connector.split("-", 1)[0] for s in seats}):
                backend._systemd_run(f"msa-dlm-{card}", [dlm, f"/dev/dri/{card}"], properties=["Restart=on-failure", "RestartSec=1s"])
            backend.sync_devices_now(config)
            for seat in seats:
                backend._start_seat(config, seat)
            backend._start_hotplug_watcher()
            save_diag(config)
        except Exception as exc:
            persist(exc)
            backend._rollback_after_failed_start()
            raise

    backend._write_runtime_udev_rules = write_rules
    backend._wait_assignments = wait_assignments
    backend._persist_activation_error = persist
    backend.activate_now = activate
    backend._msa_runtime_patch_v2_installed = True
