from __future__ import annotations

import configparser
import shutil
from pathlib import Path

THEME_VERSION = "kde-like-v2"

PANEL_CONFIG = """# Generated by multi-seat-arch.
[General]
preferred_backend=labwc:wlroots
panels=panel1

[panel1]
plugins=fancymenu,quicklaunch,taskbar,statusnotifier,tray,volume,worldclock,showdesktop
position=Bottom
alignment=Left
size=44
length=100
lengthInPercents=true
hidable=false
theme=dark

[fancymenu]
type=fancymenu
alignment=Left
filterClear=true
autoSel=true
autoSelDelay=120

[quicklaunch]
type=quicklaunch
alignment=Left
apps\\size=3
apps\\1\\desktop=/usr/share/applications/org.kde.dolphin.desktop
apps\\2\\desktop=/usr/share/applications/qterminal.desktop
apps\\3\\desktop=%HOME%/.local/share/applications/multi-seat-session.desktop

[taskbar]
type=taskbar
alignment=Left
buttonWidth=210
closeOnMiddleClick=true
groupingEnabled=true
showIcon=true
showTitle=true
raiseOnClick=true

[statusnotifier]
type=statusnotifier
alignment=Right

[tray]
type=tray
alignment=Right

[volume]
type=volume
alignment=Right

[worldclock]
type=worldclock
alignment=Right
formatType=custom
useAdvancedManualFormat=true
customFormat=HH:mm
showTooltip=true

[showdesktop]
type=showdesktop
alignment=Right
"""

KDE_GLOBALS = """[General]
ColorScheme=BreezeDark
Name=Breeze Dark
shadeSortColumn=true

[KDE]
widgetStyle=Breeze
contrast=4

[Icons]
Theme=breeze

[Colors:Window]
BackgroundNormal=32,33,36
ForegroundNormal=239,240,241

[Colors:View]
BackgroundNormal=27,28,31
ForegroundNormal=239,240,241
DecorationFocus=61,174,233
DecorationHover=61,174,233

[Colors:Button]
BackgroundNormal=41,42,45
ForegroundNormal=239,240,241

[Colors:Selection]
BackgroundNormal=61,174,233
ForegroundNormal=255,255,255
"""

GTK_SETTINGS = """[Settings]
gtk-theme-name=Breeze-Dark
gtk-icon-theme-name=breeze
gtk-font-name=Noto Sans 10
gtk-cursor-theme-name=breeze_cursors
gtk-application-prefer-dark-theme=true
"""


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def _backup_once(path: Path) -> None:
    if not path.exists():
        return
    backup = path.with_name(path.name + ".msa-backup")
    if not backup.exists():
        try:
            shutil.copy2(path, backup)
        except OSError:
            pass


def _write_lxqt_appearance(path: Path) -> None:
    parser = configparser.ConfigParser(interpolation=None)
    parser.optionxform = str
    if path.exists():
        try:
            parser.read(path, encoding="utf-8")
        except (OSError, configparser.Error):
            parser = configparser.ConfigParser(interpolation=None)
            parser.optionxform = str
    for section in ("General", "Qt", "Palette"):
        if not parser.has_section(section):
            parser.add_section(section)
    parser.set("General", "theme", "dark")
    parser.set("General", "icon_theme", "breeze")
    parser.set("Qt", "style", "Breeze")
    colors = {
        "window_color": "#202124",
        "window_text_color": "#eff0f1",
        "base_color": "#1b1c1f",
        "text_color": "#eff0f1",
        "button_color": "#292a2d",
        "button_text_color": "#eff0f1",
        "highlight_color": "#3daee9",
        "highlighted_text_color": "#ffffff",
        "link_color": "#3daee9",
        "link_visited_color": "#9b59b6",
        "tooltip_base_color": "#31363b",
        "tooltip_text_color": "#eff0f1",
    }
    for key, value in colors.items():
        parser.set("Palette", key, value)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        parser.write(handle, space_around_delimiters=False)


def _write_qterminal_theme(path: Path) -> None:
    parser = configparser.ConfigParser(interpolation=None)
    parser.optionxform = str
    if path.exists():
        try:
            parser.read(path, encoding="utf-8")
        except (OSError, configparser.Error):
            parser = configparser.ConfigParser(interpolation=None)
            parser.optionxform = str
    if not parser.has_section("General"):
        parser.add_section("General")
    parser.set("General", "colorScheme", "Linux")
    parser.set("General", "fontFamily", "Noto Sans Mono")
    parser.set("General", "fontSize", "11")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        parser.write(handle, space_around_delimiters=False)


def _write_dark_toolkit_settings(home: Path) -> None:
    _atomic_write(home / ".config/kdeglobals", KDE_GLOBALS)
    _atomic_write(home / ".config/gtk-3.0/settings.ini", GTK_SETTINGS)
    _atomic_write(home / ".config/gtk-4.0/settings.ini", GTK_SETTINGS)


def apply_kde_like_theme(home: Path | None = None) -> bool:
    home = home or Path.home()
    marker = home / ".config/multi-seat-arch/theme-version"
    try:
        if marker.read_text(encoding="utf-8").strip() == THEME_VERSION:
            return False
    except OSError:
        pass

    lxqt = home / ".config/lxqt/lxqt.conf"
    panel = home / ".config/lxqt/panel.conf"
    qterminal = home / ".config/qterminal.org/qterminal.ini"
    kdeglobals = home / ".config/kdeglobals"
    gtk3 = home / ".config/gtk-3.0/settings.ini"
    gtk4 = home / ".config/gtk-4.0/settings.ini"
    for path in (lxqt, panel, qterminal, kdeglobals, gtk3, gtk4):
        _backup_once(path)

    _write_lxqt_appearance(lxqt)
    panel_text = PANEL_CONFIG.replace("%HOME%", str(home))
    _atomic_write(panel, panel_text)
    _write_qterminal_theme(qterminal)
    _write_dark_toolkit_settings(home)
    _atomic_write(marker, THEME_VERSION + "\n")
    return True
