from __future__ import annotations

import configparser
import shutil
from pathlib import Path

ROLLBACK_VERSION = "native-lxqt-v1"


def _restore_backup(path: Path) -> bool:
    backup = path.with_name(path.name + ".msa-backup")
    if not backup.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(backup, path)
    return True


def _looks_like_generated_panel(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return "Generated by multi-seat-arch" in text or (
        "preferred_backend=labwc:wlroots" in text
        and "plugins=fancymenu,quicklaunch,taskbar" in text
    )


def _looks_like_generated_kdeglobals(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return (
        "ColorScheme=BreezeDark" in text
        and "BackgroundNormal=32,33,36" in text
        and "DecorationFocus=61,174,233" in text
    )


def _looks_like_generated_gtk(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return (
        "gtk-theme-name=Breeze-Dark" in text
        and "gtk-icon-theme-name=breeze" in text
        and "gtk-cursor-theme-name=breeze_cursors" in text
    )


def _remove_generated_lxqt_keys(path: Path) -> None:
    if not path.exists():
        return
    parser = configparser.ConfigParser(interpolation=None)
    parser.optionxform = str
    try:
        parser.read(path, encoding="utf-8")
    except (OSError, configparser.Error):
        return

    generated = False
    if parser.has_section("General"):
        if parser.get("General", "theme", fallback="") == "dark":
            parser.remove_option("General", "theme")
            generated = True
        if parser.get("General", "icon_theme", fallback="") in {"breeze", "breeze-dark"}:
            parser.remove_option("General", "icon_theme")
            generated = True
    if parser.has_section("Qt") and parser.get("Qt", "style", fallback="") == "Breeze":
        parser.remove_option("Qt", "style")
        generated = True
    if parser.has_section("Palette"):
        project_palette = {
            "window_color": "#202124",
            "window_text_color": "#eff0f1",
            "base_color": "#1b1c1f",
            "text_color": "#eff0f1",
            "button_color": "#292a2d",
            "button_text_color": "#eff0f1",
            "highlight_color": "#3daee9",
            "highlighted_text_color": "#ffffff",
            "link_color": "#3daee9",
            "link_visited_color": "#9b59b6",
            "tooltip_base_color": "#31363b",
            "tooltip_text_color": "#eff0f1",
        }
        for key, value in project_palette.items():
            if parser.get("Palette", key, fallback="") == value:
                parser.remove_option("Palette", key)
                generated = True

    if not generated:
        return

    for section in list(parser.sections()):
        if not parser.items(section):
            parser.remove_section(section)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        parser.write(handle, space_around_delimiters=False)


def _remove_generated_qterminal_keys(path: Path) -> None:
    if not path.exists():
        return
    parser = configparser.ConfigParser(interpolation=None)
    parser.optionxform = str
    try:
        parser.read(path, encoding="utf-8")
    except (OSError, configparser.Error):
        return
    if not parser.has_section("General"):
        return
    changed = False
    for key, value in (
        ("colorScheme", "Linux"),
        ("fontFamily", "Noto Sans Mono"),
        ("fontSize", "11"),
    ):
        if parser.get("General", key, fallback="") == value:
            parser.remove_option("General", key)
            changed = True
    if changed:
        with path.open("w", encoding="utf-8") as handle:
            parser.write(handle, space_around_delimiters=False)


def ensure_panel_backend(home: Path | None = None) -> None:
    """Keep only the functional wlroots backend hint; do not style the panel."""
    home = home or Path.home()
    path = home / ".config/lxqt/panel.conf"
    if not path.exists():
        return
    parser = configparser.ConfigParser(interpolation=None, delimiters=("=",))
    parser.optionxform = str
    try:
        parser.read(path, encoding="utf-8")
    except (OSError, configparser.Error):
        return
    if not parser.has_section("General"):
        parser.add_section("General")
    parser.set("General", "preferred_backend", "labwc:wlroots")
    with path.open("w", encoding="utf-8") as handle:
        parser.write(handle, space_around_delimiters=False)


def restore_native_lxqt_theme(home: Path | None = None) -> bool:
    """Undo project-owned theme overrides once and return control to LXQt.

    Existing pre-theme files are restored from .msa-backup. If a file did not
    exist before the theme experiment, only configurations that still match the
    project-generated signatures are removed. After this migration the project
    no longer sets an LXQt/Qt/GTK/icon/cursor theme.
    """
    home = home or Path.home()
    state_dir = home / ".config/multi-seat-arch"
    marker = state_dir / "theme-version"
    rollback_marker = state_dir / "theme-rollback-version"
    try:
        if rollback_marker.read_text(encoding="utf-8").strip() == ROLLBACK_VERSION:
            ensure_panel_backend(home)
            return False
    except OSError:
        pass

    managed = [
        home / ".config/lxqt/lxqt.conf",
        home / ".config/lxqt/panel.conf",
        home / ".config/qterminal.org/qterminal.ini",
        home / ".config/kdeglobals",
        home / ".config/gtk-3.0/settings.ini",
        home / ".config/gtk-4.0/settings.ini",
    ]
    restored = {path: _restore_backup(path) for path in managed}

    lxqt, panel, qterminal, kdeglobals, gtk3, gtk4 = managed
    if not restored[lxqt]:
        _remove_generated_lxqt_keys(lxqt)
    if not restored[panel] and _looks_like_generated_panel(panel):
        panel.unlink(missing_ok=True)
    if not restored[qterminal]:
        _remove_generated_qterminal_keys(qterminal)
    if not restored[kdeglobals] and _looks_like_generated_kdeglobals(kdeglobals):
        kdeglobals.unlink(missing_ok=True)
    for gtk in (gtk3, gtk4):
        if not restored[gtk] and _looks_like_generated_gtk(gtk):
            gtk.unlink(missing_ok=True)

    marker.unlink(missing_ok=True)
    state_dir.mkdir(parents=True, exist_ok=True)
    rollback_marker.write_text(ROLLBACK_VERSION + "\n", encoding="utf-8")
    ensure_panel_backend(home)
    return True
